_target_: src.models.monke_module.MonkeLightningModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

importance:
  _target_: src.models.components.linear_regression.TrialwiseLinearRegression
  ablations: []
  num_regressors: 7
  num_stimuli: 4
# compile model for faster training with pytorch 2.0
compile: false

num_particles: 5
