_target_: src.models.svi_module.SviLightningModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-3

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

importance:
  _target_: src.models.components.linear_regression.TrialwiseLinearRegression
  ablations: []
  num_regressors: 4
  num_stimuli: 4
# compile model for faster training with pytorch 2.0
compile: false

num_particles: 5
